### ISSUE TITLE
ValueError: non-integer arg 1 for randrange()

### ISSUE THREAD

**Issue by summerinsect** [ty-me/DjangoCaptcha#3]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(_args, *_kwargs)
  File "/Users/wangyidong1/Documents/workspace/Strategy/UserManager/views.py", line 162, in code
    return ca.display()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/DjangoCaptcha/**init**.py", line 144, in display
    random.randrange(3*self.img_width/4,self.img_width),
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/random.py", line 182, in randrange
    raise ValueError("non-integer arg 1 for randrange()")
ValueError: non-integer arg 1 for randrange()

**Comment by yohn89** [comment]
Ensure the type of attributes `img_width ` and `img_width ` you set is `int`, not string.
e.g.

GOOD:

```
ca  = Captcha(request)
ca.img_width = 100
ca.img_height = 30
```

BAD :

```
ca.img_width = '100'
ca.img_height = '30px'
```
